spring:
  jpa:
    database: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  profiles:
    active: @activatedProperties@
app:
  datasource:
    jdbc-url: jdbc:h2:mem:testdb
    username: sa
jpa