server:
  port: 9000
  address: "localhost"
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  profiles:
    active: @activatedProperties@

