server:
  port: 9191
  address: localhost

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: INGREDIENT-SERVICE
          uri: lb://INGREDIENT-SERVICE
          predicates:
            - Path=/ingredients/**
          filters:
            - name: CircuitBreaker
              args:
                name: INGREDIENT-SERVICE
                fallbackuri: forward:/ingredientServiceFallBack
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
          filters:
            - name: CircuitBreaker
              args:
                name: RATING-SERVICE
                fallbackuri: forward:/ratingServiceFallBack


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: false
    hostname: localhost
