version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 51646:51646