spring:
  application:
    name: USER-SERVICE
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  profiles:
    active: @activatedProperties@
  zipkin:
    base-url: http://127.0.0.1:9411/
server:
  port: 9092
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: false
    hostname: localhost