server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    ip-address: 192.168.0.122
    prefer-ip-address: true
spring:
  application:
    name: discovery-server
