uspring:
  jpa:
    database: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/ingredientservicedb;AUTO_SERVER=TRUE
    username: sa
  h2:
    console:
      enabled: true
app:
  datasource:
    jdbc-url: jdbc:h2:./data/ingredientservicedb;AUTO_SERVER=TRUE
    username: sa
debug: true